### ISSUE TITLE
Outer material selection

### ISSUE THREAD

**Issue by akshaydr** [akshaydr/Esfera#2]
Selecting the material for covering on the skeleton of robot.

**Comment by akshaydr** [comment]
Aluminum was one of the option we have after todays meeting.

**Comment by shriprad** [comment]
For outer material selection we need to  concentrate on friction good the friction good the rolling

Here are the links which can give us the differnt kind of materials and their co-efficent of friction


http://www.engineershandbook.com/Tables/frictioncoefficients.htm

http://www.engineeringtoolbox.com/friction-coefficients-d_778.html

**Comment by akshaydr** [comment]
Outer material selection conclusion:
Aluminium for skeleton and aluminium sheets for outer covering. Rubber is put on it to increase friction.

If any queries, then team members can rise the issue again.
